### ISSUE TITLE
Move Classes

### ISSUE THREAD

**Issue by kuhaku4** [mucsci-students/2024sp-420-JavaB#171]
Move Classes: Class Box Moves

When the user click and drags a class box it will follow their cursor.

Primary: @jrlease-03 

Secondary: @kuhaku4 

Size: Radagon

Actual Size: (fib number after completion)

Actual Time: (in minutes or hours -- after completion)

**Comment by BasilrockMU** [comment]
Eric and joshua worked on it for 6 hours.
