### ISSUE TITLE
Save Locations: When box is moved the location is saved when saving.

### ISSUE THREAD

**Issue by kuhaku4** [mucsci-students/2024sp-420-JavaB#175]
Save Locations: Location is saved when saving.

When I save the program the location of the class boxes is saved as well.

Primary: @kuhaku4 

Secondary: @CullenIsntHere 

Size: Morgott

Actual Size: (fib number after completion)

Actual Time: (in minutes or hours -- after completion)

**Comment by BasilrockMU** [comment]
Kuhaku: Friday and Saturday an hour and a half on both days.
