### ISSUE TITLE
macOS menu bar is at the top of the screen and not in the window.

### ISSUE THREAD

**Issue by kuhaku4** [mucsci-students/2024sp-420-JavaB#237]
General Fixes

When the user is on macOS the menu bar should appear in the integrated menu at the top of the screen rather than in the window.

Primary: @CullenIsntHere 

Secondary: @kuhaku4 

Size: Rykard?

Actual Size: (fib number after completion)

Actual Time: (in minutes or hours -- after completion)

**Comment by willkill07** [comment]
This issue was opened 3 weeks ago but has not been updated
